<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>CRUD MVC</title>
</head>
<body>
     <ul>
            <li><a href="index.php?route=list">Liste des utilisateurs</a></li>
            <li><a href="index.php?route=create_user">Créer un utilisateur</a></li>
            <li><a href="index.php?route=show_user">Afficher un utilisateur</a></li>
            <li><a href="index.php?route=update_user">Modifier un utilisateur</a></li>
           
        </ul>
    
</body>
<main>
    
    <?php require $template . '.phtml'; ?>
</main>
</html>