<h1>Créer un utilisateur</h1>

<form action="index.php?route=check_create_user" method="post">
    <div>
        <label for="email">Email :</label>
        <input type="email" name="email" id="email" required>
    </div>
    <div>
        <label for="first_name">Prénom :</label>
        <input type="text" name="first_name" id="first_name" required>
    </div>
    <div>
        <label for="last_name">Nom :</label>
        <input type="text" name="last_name" id="last_name" required>
    </div>
    <div>
        <button type="submit">Créer l'utilisateur</button>
    </div>
</form>